version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ..." ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT_TYPE=docker
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/doctors/filter/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s


volumes:
  postgres_data: